apiVersion: v1
kind: Service
metadata:
  name: hello-kube-service-node-port
  labels:
    app: hello-kube
    components: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31515
  selector:
    app: hello-kube
    components: web