apiVersion: v1
kind: Service
metadata:
  name: hello-kube-service
  labels:
    app: hello-kube
    components: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-kube
    components: web